### PR TITLE
Adding context

### PR DESCRIPTION
**Pull request by jerels**
Attempting to add some context around the use of the module.

This is what I've got so far for the README, looking to see if it fits. As well as if there's more to add?

### CODE REVIEW

**Comment by jerels** [comment]
i'm also curious to know how to go about formatting an example of usage.

**Review by kilbergr — APPROVED** [review]
Looking VERY good to me. Thank you for these changes.
I have a non-blocking q:
What does it mean that the target_instance_ip is TEMPORARY? Is it that you intend to remove that from the module?

**Comment by jerels** [comment]
> Looking VERY good to me. Thank you for these changes.
> I have a non-blocking q:
> What does it mean that the target_instance_ip is TEMPORARY? Is it that you intend to remove that from the module?

i'm not entirely sure? i think it might be a function of the module? it's something that was there from when @eeeady built it

**Comment by kilbergr** [comment]
Kk in that case, I'd say it's out of the scope of this ticket. Go ahead and merge!

**Pull request merged**
